### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by zjn000** [Aierui/tp-admin#3]
今天下载后安装，结果get_menu_child_html（$list）中的$list并没拿到值，发现菜单项是从缓存Cache::get('menu');取出来的，但问题是一开始是没有缓存数据的，所以出现报错，希望大大可以优化下

**Comment by Aierui** [comment]
@zjn000 
初次配置需要手动调用 http://yourdomain/admin/menu/cache
因为菜单是缓存在本地，希望能够帮助到你

过几天新版本不存在这个问题

当然这个问题会在之后完善
