### ISSUE TITLE
希望实现例子

### ISSUE THREAD

**Issue by zjn000** [Aierui/tp-admin#4]
希望将用户建议那里的表格数据不要一次性加载，实现从服务器获取数据进行分页加载，数据量庞大时加载缓慢，求DEMO

**Comment by Aierui** [comment]
@zjn000 
这个简单，首先在后台控制器index方法中 返回增加一个字段 total，然后在index.html中将data-side-pagination=“client” 改成data-side-pagination=“server”


效果如图
`
	public function index()
	{

		if (request()->isAjax()) {
			$data = request()->param();
			$map = "1 = 1";
			$rows = $this->comment->where($map)->order('create_time desc')->select();
			$total = count($rows);
			foreach ($rows as $key => $value) {
				$rows[$key]['create_time'] = date("Y-m-d H:i:s" , $value['create_time']);
			}
			return ['rows' => $rows, 'total' => $total];
		}
		return $this->fetch();
	}
`


`
<table id="table" data-toggle="gridview" class="table" data-url="/{$Request.module}/{$Request.controller}" data-toolbar="#toolbar" data-show-columns="true" data-page-size="10" data-page-list="[10, 25, 50, All]" data-unique-id="id" data-pagination="true" data-side-pagination="client"  data-search="true">
    <thead>
        <tr>
            <th data-width="10"  data-align="center"  data-checkbox="true"></th>
            <th data-field="name" >称呼</th>
            <th data-field="content">留言内容</th>
            <th data-field="create_time">时间</th>
        </tr>
    </thead>
</table>`
